proagro_app/urls.py
from django.contrib import admin
from django.urls import include, path
from proagro_app import views


app_name = 'view_proagro'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('novo_cadastro', views.novo_cadastro, name = 'novo_cadastro'),
    path('cadastros', views.listar_cadastros, name = 'listar_cadastros'),
    path('editar/<int:pk>', views.editar_cadastro, name = 'editar_cadastro'),
    path('excluir/<int:pk>', views.excluir_cadastro, name = 'excluir_cadastro'),

]

proagro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('proagro/', include('proagro_app.urls')),
    path('admin/', admin.site.urls),
    path('', views.home),
]

proagro_app/models.py
from django.db import models

# Create your models here.
class Cadastro(models.Model):

    nome_produtor = models.CharField(max_length=254)
    email_produtor = models.EmailField(max_length=254)
    cpf_produtor = models.CharField(max_length = 11)
    lat_lavoura = models.CharField(max_length = 20)
    long_lavoura = models.CharField(max_length = 20)
    tipo_lavoura = models.CharField(max_length = 20)
    data_colheita = models.DateField()
    evento = models.CharField(max_length = 20)
    status = models.CharField(max_length = 20)
    
    data_solicitacao = models.DateField(auto_now_add = True)
    data_ultima_modificacao = models.DateField(auto_now = True)
    id_analista = models.CharField(max_length = 5)

proagro_app/views.py
import datetime
from django.shortcuts import render, redirect
from .data_validation import DictCadastro
from .models import Cadastro
from haversine import haversine
from pydantic import ValidationError
# Create your views here.
# import pdb; pdb.set_trace()

def checar_distancia(lat_a,lon_a,lat_b,lon_b):
    loc_a = (float(lat_a),float(lon_a))
    loc_b = (float(lat_b),float(lon_b))
    return haversine(loc_a, loc_b)

def novo_cadastro(request):
    if request.method == 'POST':
        '''Cria um dicionario para a adição dos valores, adiciona um valor padrão ao status da solicitação'''
        dict_form = {"status" : "Aguardando"}
        for key, value in request.POST.items():
            '''Verifica se o input possui algum valor vazio. Esse verificação já é feita no front, mas por garantia tambem está sendo feita no backend.'''
            if value != "":
                dict_form[key] = value
            else:
                return render(request, 'proagro_app/novo_cadastro.html',{'modal_msg':"Todos os campos precisam ser preenchidos!"})


        '''Realiza o tratamento de valores, caso resulte em erro, o programa avisa o usuario.
        Esse erro dificilmente seria causado pelo uso no frontend, pois a validação do CPF já está sendo feita antes de chegar nesse ponto, e a entrada da data não é feita de maneira "escrita".
        '''   
        try:
            dict_form_validado = DictCadastro(**dict_form)
        except ValidationError as e:
            return render(request, 'proagro_app/novo_cadastro.html',{'modal_msg':e})
        
        try:
            colheita_mesma_data = Cadastro.objects.all().filter(data_colheita = dict_form_validado.data_colheita)
            for colheita in colheita_mesma_data:
                lat_a = dict_form_validado.lat_lavoura
                lon_a = dict_form_validado.long_lavoura
                
                lat_b = colheita.lat_lavoura
                lon_b = colheita.long_lavoura
                
                if checar_distancia(lat_a,lon_a,lat_b,lon_b) <= 10:
                    if dict_form_validado.evento != colheita.evento:
                        return render(request, 'proagro_app/novo_cadastro.html',{'modal_msg':f"Um cadastro foi localizado com a mesma data de colheita, a menos de 10 km da propriedade atual, com eventos divergentes. CPF do produtor {colheita.cpf_produtor}"})
        except:
            '''Nenhuma colheita foi feita nessa data'''
            pass
        
        '''caso esteja tudo ok, um novo registro será criado, caso contrario, o usuario será notificado.'''
        try:
            cadastro = Cadastro()
            cadastro.nome_produtor = dict_form_validado.nome_produtor
            cadastro.email_produtor = dict_form_validado.email_produtor
            cadastro.cpf_produtor = dict_form_validado.cpf_produtor
            cadastro.lat_lavoura = dict_form_validado.lat_lavoura
            cadastro.long_lavoura = dict_form_validado.long_lavoura
            cadastro.tipo_lavoura = dict_form_validado.tipo_lavoura
            cadastro.data_colheita = dict_form_validado.data_colheita
            cadastro.evento = dict_form_validado.evento
            cadastro.status = dict_form_validado.status
            cadastro.id_analista = 1
            cadastro.save(force_insert=True)    
            return render(request, 'proagro_app/novo_cadastro.html',{'modal_msg':"Cadastro realizado com sucesso!"})
        except Exception as e:
            return render(request, 'proagro_app/novo_cadastro.html',{'modal_msg':e})
    else:
        return render(request, 'proagro_app/novo_cadastro.html')
    
# p = Cadastro(first_name="Bruce", last_name="Springsteen")
# p.save(force_insert=True)
        
def criar_lista_cadastros(cadastros):
    dict_cadastros = [cadastro for cadastro in cadastros.values()]
    dict_icons = {
        "CHUVA EXCESSIVA":"water_drop",
        "GEADA":"ac_unit",
        "GRANIZO":"cloudy_snowing",
        "SECA":"sunny",
        "VENDAVAL":"air",
        "RAIO":"bolt",
        } 
    for cadastro in dict_cadastros:
        cadastro['data_colheita'] = cadastro['data_colheita'].strftime("%d/%m/%Y")
        temp_cpf = cadastro["cpf_produtor"]
        cadastro['cpf_produtor'] = '{}.{}.{}-{}'.format(temp_cpf[:3], temp_cpf[3:6], temp_cpf[6:9], temp_cpf[9:])
        cadastro['evento_icone'] = dict_icons[cadastro['evento']]
    return dict_cadastros
        
def listar_cadastros(request):

    cadastros = Cadastro.objects.all().order_by('-data_colheita')
    lista_cadastros_todos = criar_lista_cadastros(cadastros)
    
    if request.method == 'POST':
        cpf = request.POST.get("cpf_search","").replace(".","").replace("-","")
        cadastros = Cadastro.objects.all().filter(cpf_produtor = cpf).order_by('-data_colheita')
        if len(cadastros) == 0:
            return render(request, 'proagro_app/listar_cadastros.html', {'modal_msg':"Nenhum cadastro para esse CPF",'cadastros':lista_cadastros_todos})
            
        lista_cadastros = criar_lista_cadastros(cadastros)
        return render(request, 'proagro_app/listar_cadastros.html', {'cadastros':lista_cadastros})
    
        # cadastro['data_colheita'] = datetime.strptime(v,"%Y-%m-%d")

    return render(request, 'proagro_app/listar_cadastros.html', {'cadastros':lista_cadastros_todos})

def editar_cadastro(request, pk):
    
    cadastro = Cadastro.objects.get(pk = pk)
    cadastro_dict = cadastro.__dict__


    cadastro_dict['data_colheita'] = cadastro_dict['data_colheita'].strftime("%Y-%m-%d")
    temp_cpf = cadastro_dict['cpf_produtor']
    cadastro_dict['cpf_produtor'] = '{}.{}.{}-{}'.format(temp_cpf[:3], temp_cpf[3:6], temp_cpf[6:9], temp_cpf[9:])
    # cadastro_dict['evento'] = dict_icons[cadastro_dict['evento']]
    
    
    if request.method == 'POST':
        print(request)
        dict_form = {'cpf_produtor':cadastro_dict['cpf_produtor']}
        for key, value in request.POST.items():
            '''Verifica se o input possui algum valor vazio. Esse verificação já é feita no front, mas por garantia tambem está sendo feita no backend.'''
            if value != "":
                dict_form[key] = value
            else:
                return render(request, 'proagro_app/editar_cadastro.html',{'cadastro':cadastro_dict,'modal_msg':"Todos os campos precisam ser preenchidos!"})
            
        '''Realiza o tratamento de valores, caso resulte em erro, o programa avisa o usuario.'''   
        try:
            dict_form_validado = DictCadastro(**dict_form)
        except ValidationError as e:
            return render(request, 'proagro_app/editar_cadastro.html',{'cadastro':cadastro_dict, 'modal_msg':e})
        
        try:
            cadastro.nome_produtor = dict_form_validado.nome_produtor
            cadastro.cpf_produtor = dict_form_validado.cpf_produtor
            cadastro.email_produtor = dict_form_validado.email_produtor
            cadastro.lat_lavoura = dict_form_validado.lat_lavoura
            cadastro.long_lavoura = dict_form_validado.long_lavoura
            cadastro.tipo_lavoura = dict_form_validado.tipo_lavoura
            cadastro.data_colheita = dict_form_validado.data_colheita
            cadastro.evento = dict_form_validado.evento
            cadastro.status = dict_form_validado.status
            cadastro.id_analista = 1
            cadastro.save()    
            return render(request, 'proagro_app/index.html',{'modal_msg':"Cadastro editado com sucesso!"})
        except Exception as e:
            return render(request, 'proagro_app/index.html',{'modal_msg':e})
            # return render(request, 'proagro_app/editar_cadastro.html',{'modal_msg':e})
        

    
    return render(request, 'proagro_app/editar_cadastro.html', {'cadastro':cadastro_dict})

def excluir_cadastro(request, pk):
    try:
        Cadastro.objects.get(pk = pk).delete()
    except:
        pass
    
    return redirect("view_proagro:listar_cadastros")


def home(request):
    return render(request, 'proagro_app/index.html')

proagro_app/templates/proagro_app/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <title>Bootstrap demo</title> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="{%  static  'css/proagro_app/style.css'  %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand mx-3" href="./">Proagro</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'view_proagro:listar_cadastros' %}">Cadastros</a>
              </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'view_proagro:novo_cadastro' %}">Novo Cadastro</a>
            </li>

        </div>

      </nav>


    {% block content %}
    {% endblock %}
    
    
    {% comment %} <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
    <script>
    window.onload = function () {  
      const msg_modal = '{{ modal_msg }}';
      if (msg_modal != ""){
        bootbox.alert(msg_modal);
      }
    }
  </script>
    {% block script %} 
    {% endblock %}
  </body>
</body>

</html>

{% comment %} 
$("#inputEvento").change(function(){
  $(this).children("option:selected").val() = {{cadastro.evento}};
}); {% endcomment %}

proagro_app/templates/proagro_app/editar_cadastro.html
{% extends 'proagro_app/base.html' %}

{% block content %}


<div class = "container col-lg-6 col-md-8 col-sm-10">
  
<form method="post" name = "form_editar">
  {% csrf_token %}
  <div class="row">
    <div class="form-group col-md-8">
      <label for="inputNome">Nome</label>
      <input type="text" class="form-control" id="inputNome" name = "nome_produtor" required>
    </div>
    <div class="form-group col-md-4">
      <label for="inputCPF">CPF</label>
      <input type="text" class="form-control" id="inputCPF" name = "cpf_produtor" disabled >
    </div>
  </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" name = "email_produtor" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputConfEmail">Confirmar Email</label>
        <input type="email" class="form-control" id="inputConfEmail" name = "confi_email_produtor"  required>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <label for="inputTipo">Tipo Lavoura</label>
        <input type="text" class="form-control" id="inputTipo" name = "tipo_lavoura" required>
      </div>



      <div class="form-group col-md-4">
        <label for="inputEvento">Evento</label>
        <select id="inputEvento" name = "evento" class="form-control" required>
          <option value = "CHUVA EXCESSIVA">CHUVA EXCESSIVA</option>
          <option value = "GEADA">GEADA</option>
          <option value = "GRANIZO">GRANIZO</option>
          <option value = "SECA">SECA</option>
          <option value = "VENDAVAL">VENDAVAL</option>
          <option value = "RAIO">RAIO</option>
        </select>
      </div>

      <div class="form-group col-md-4">
        <label for="inputData">Data Colheita</label>
        <input id="inputData" name = "data_colheita" class="form-control" type="date">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <label for="inputLat">Latitude</label>
        <input type="text" class="form-control" id="inputLat" name = "lat_lavoura" required>
      </div>
      <div class="form-group col-md-4">
        <label for="inputLong">Longitude</label>
        <input type="text" class="form-control" id="inputLong" name="long_lavoura" required>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <label for="inputStatus">Status</label>
          <select id="inputStatus" name = "status" class="form-control" required>
            <option value = "Aguardando">Aguardando</option>
            <option value = "Negado">Negado</option>
            <option value = "Glosa parcial">Glosa parcial</option>
            <option value = "Aprovado">Aprovado</option>
          </select>
        </div>
      </div>
    <br>
    
    <button type="button" class="btn btn-primary" onclick="confirmar_alteracoes_modal({{cadastro.id}})">Salvar</button>

  </form>

</div>
  
{% endblock %}
  

{% block script %} 
<script>
  
  window.onload = function () {    
    document.getElementById("inputEvento").value = "{{ cadastro.evento }}";
    document.getElementById("inputStatus").value = "{{ cadastro.status }}";
    document.getElementById("inputData").value = "{{ cadastro.data_colheita }}";
    document.getElementById("inputNome").value = "{{ cadastro.nome_produtor }}";
    document.getElementById("inputCPF").value = "{{ cadastro.cpf_produtor }}";
    document.getElementById("inputEmail").value = "{{ cadastro.email_produtor }}";
    document.getElementById("inputConfEmail").value = "{{ cadastro.email_produtor }}";
    document.getElementById("inputData").value = "{{ cadastro.data_colheita }}";
    document.getElementById("inputLat").value = "{{ cadastro.lat_lavoura }}";
    document.getElementById("inputLong").value = "{{ cadastro.long_lavoura }}";
    document.getElementById("inputTipo").value = "{{ cadastro.tipo_lavoura }}";
  }
  
  function confirmar_alteracoes_modal(id){
    bootbox.confirm({
        message: "Confirmar edições no cadastro?",
        centerVertical: true,
        buttons: {
            confirm: {
                label: 'Confirmar',
                className: 'btn-success'
            },
            cancel: {
                label: 'Voltar',
                className: 'btn-danger'
            }
        },
        callback: function (result) {
          if (result == true)
          {
              document.form_editar.submit();
          }
      }
    });
};




</script>
{% endblock %}

proagro_app/templates/proagro_app/index.html
{% extends 'proagro_app/base.html' %}

{% block content %}

    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
          <h1 class="display-4 fw-normal">ProAgro</h1>
          <br>
          <p class="lead fw-normal">O Proagro Fácil é um sistema da Softfocus que facilita o gerenciamento de
            Proagro (Programa de Garantia da Atividade Agropecuária). O Proagro é um
            programa administrado pelo Banco Central do Brasil, que visa exonerar o produtor
            rural de obrigações financeiras relativas a operações de crédito, em casos de
            ocorrência de perdas nas lavouras.</p>
          <a class="btn btn-outline-secondary" href="{% url 'view_proagro:listar_cadastros' %}">Visualizar Cadastros</a>
          <a class="btn btn-outline-secondary" href="{% url 'view_proagro:novo_cadastro' %}">Realizar Novo Cadastro</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>

{% endblock %}

proagro_app/templates/proagro_app/listar_cadastros.html
{% extends 'proagro_app/base.html' %}

{% block content %}



<br>


<div class = "container col-lg-10 col-md-8 col-sm-10">

    <form method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="search" class="form-control rounded" placeholder="Buscar por CPF" aria-label="Search" aria-describedby="search-addon" name = "cpf_search" />
            <button type="submit" class="btn btn-outline-primary">Buscar</button>
        </div>

    </form>
<br>
<br>


{% for cadastro in cadastros %}
    <div class="accordion my-2" id="accordion_{{ cadastro.id }}">
        {% if cadastro.status == 'Negado' %}
            <div class="card border-danger">
        {% elif cadastro.status == 'Aguardando' %}
            <div class="card border-info">
        {% elif cadastro.status == 'Glosa parcial' %}
            <div class="card border-warning">
        {% elif cadastro.status == 'Aprovado' %}
            <div class="card border-success">
        {% else %}
            <div class="card">
        {% endif %}

        <div class="card-header" id="heading_{{ codigo.id }}">
            <div type="button" data-toggle="collapse" data-target="#colapse_{{cadastro.id}}" aria-expanded="false" aria-controls="colapse_{{cadastro.id}}">

                <a href="#" class="list-group-item list-group-item-action flex-column">
                <div class="d-flex w-100 justify-content-between align-items-center">

                    <div class="mb-1 col-2">
                        <spam class="small">Produtor</spam>
                        <h5>{{ cadastro.nome_produtor }}</h5>
                    </div>

                    <div class="mb-1 col-2">
                        <spam class="small">CPF</spam>
                        <h6> {{ cadastro.cpf_produtor }}</h6>
                    </div>             
                    
                    <div class="mb-1 col-1">
                        <spam class="small">Colheita</spam>
                        <h6><time datetime="YYYY-MM-DD"> {{ cadastro.data_colheita }}</h6>
                    </div>
                    <div class="mb-1 col-1">
                        <spam class="small">Status</spam>
                        <h6><time datetime="YYYY-MM-DD"> {{ cadastro.status }}</h6>
                    </div>
                                    
                    <div class="d-flex justify-content-center align-items-center">
                        <i class=" mb-1 col-1 material-icons">{{ cadastro.evento_icone }}</i>
                    </div>

                    <div class=" mb-1 col-1 btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-info" onclick="window.location='{% url 'view_proagro:editar_cadastro' cadastro.id %}';"><i class="material-icons">edit</i></button>
                        <button type="button" class="btn btn-danger" onclick="show_delete_modal({{cadastro.id}})"><i class="material-icons">delete</i></button>
                    </div>

                </div>
                </a>
            </div>
      </div>
  
      <div id="colapse_{{cadastro.id}}" class="collapse" aria-labelledby="heading_{{ codigo.id }}" data-parent="#accordion_{{ cadastro.id }}">
        <div class="card-body">
            <h5>Nome Produtor: {{ cadastro.nome_produtor }}</h5>
            <h6>CPF: {{ cadastro.cpf_produtor }}</h6>
            <h6>Data Colheita: <time datetime="YYYY-MM-DD"> {{ cadastro.data_colheita }}</h6>
            <h6>Status: {{ cadastro.status }}</h6>
            <h6>Evento: {{ cadastro.evento }}  <i class=" mb-1 col-1 material-icons">{{ cadastro.evento_icone }}</i></h6>
            <h6>Lavoura: {{ cadastro.tipo_lavoura }}</h6>
            <h6>Latitude: {{ cadastro.lat_lavoura }}</h6>
            <h6>Longitude: {{ cadastro.long_lavoura }}</h6>
            
        </div>
      </div>
    </div>
    
    </div>

    {% endfor %}


{% endblock %}


{% block script %}

<script>


    function show_delete_modal(id){
        bootbox.confirm({
            message: "Deseja realizar a exlusão do cadastro?",
            centerVertical: true,
            buttons: {
                confirm: {
                    label: 'Excluir',
                    className: 'btn-danger'
                },
                cancel: {
                    label: 'Voltar',
                    className: 'btn'
                }
            },
            callback: function (result) {
                if (result == true)
                {
                    window.location = 'excluir/'+id;
                }
            }
        });
    };

</script>

{% endblock %}

proagro_app/templates/proagro_app/novo_cadastro.html
{% extends 'proagro_app/base.html' %}

{% block content %}


<div class = "container col-lg-6 col-md-8 col-sm-10">
  
<form method="post" name="form_cadastro">
  {% csrf_token %}
  <div class="row">
    <div class="form-group required col-md-8">
      <label for="inputNome">Nome</label>
      <input type="text" class="form-control" id="inputNome" name = "nome_produtor" placeholder="Nome" />
    </div>
    <div class="form-group required col-md-4">
      <label for="inputCPF">CPF</label>
      <input type="text" class="form-control" id="inputCPF" name = "cpf_produtor" placeholder="CPF" />
    </div>
  </div>

    <div class="row">
      <div class="form-group required col-md-6">
        <label for="inputEmail">Email</label>
        <input type="text" class="form-control" id="inputEmail" name = "email_produtor" placeholder="Email" />
      </div>
      <div class="form-group required col-md-6">
        <label for="inputConfEmail">Confirmar Email</label>
        <input type="text" class="form-control" id="inputConfEmail" name = "confi_email_produtor" placeholder="Confirmar Email" />
      </div>
    </div>

    <div class="row">
      <div class="form-group required col-md-4">
        <label for="inputTipo">Tipo Lavoura</label>
        <input type="text" class="form-control" id="inputTipo" name = "tipo_lavoura" placeholder="Milho, Soja, Trigo..." />
      </div>

      <div class="form-group required col-md-4">
        <label for="inputEvento">Evento</label>
        <select id="inputEvento" name = "evento" class="form-control" />
          <option selected>CHUVA EXCESSIVA</option>
          <option>GEADA</option>
          <option>GRANIZO</option>
          <option>SECA</option>
          <option>VENDAVAL</option>
          <option>RAIO</option>
        </select>
      </div>

      <div class="form-group required col-md-4">
        <label for="inputData">Data Colheita</label>
        <input id="inputData" name = "data_colheita" class="form-control" type="date" />
      </div>
    </div>

    

    <div class="row">
      <div class="form-group required col-md-4">
        <label for="inputLat">Latitude</label>
        <input type="text" class="form-control" id="inputLat" name = "lat_lavoura" placeholder="-00.00000" />
      </div>
      <div class="form-group required col-md-4">
        <label for="inputLong">Longitude</label>
        <input type="text" class="form-control" id = "inputLong" name="long_lavoura" placeholder="-00.00000" />
      </div>
    </div>


    <br>
    <button type="button" class="btn btn-primary" onclick="validar_form()">Salvar</button>

  </form>

</div>
  
{% endblock %}


{% block script %}

<script>



  


function validar_form(){

  var FormValido = true;
  const cpf = document.getElementById("inputCPF").value;
  const email = document.getElementById("inputEmail").value;
  const conf_email = document.getElementById("inputConfEmail").value;
  
  
  if (checar_required() == false)
  {
    FormValido = false;
    bootbox.alert("Todos os campos precisam ser preenchidos!");
    return
  }
  if (validar_cpf(cpf) == false)
  {
    FormValido = false;
    bootbox.alert("CPF inserido é inválido!");
    return
  }

  if (validar_email(email) == false)
  {
    FormValido = false;
    bootbox.alert("E-mail inserido é inválido!");
    return
  }
  if (email.localeCompare(conf_email) != 0)
  {
    FormValido = false;
    bootbox.alert("E-mail de confirmação não é igual ao e-mail inserido!");
    return
  }

  if (FormValido == true)
  {
    document.form_cadastro.submit();
  }
}


function validar_cpf(strCPF) {

  const numCPF = strCPF.replace(/\./g, "").replace(/\-/g, "");
  var Soma;
  var Resto;

  if (numCPF == "00000000000") 
  {
    return false;
  }
  Soma = 0;
  for (i=1; i<=9; i++) 
  {
    Soma = Soma + parseInt(numCPF.substring(i-1, i)) * (11 - i);
  }
  Resto = (Soma * 10) % 11;

  if ((Resto == 10) || (Resto == 11))  
  {
    Resto = 0;
  }
  if (Resto != parseInt(numCPF.substring(9, 10))) 
  {
    return false;
  }

  Soma = 0;
  for (i = 1; i <= 10; i++) 
  {
    Soma = Soma + parseInt(numCPF.substring(i-1, i)) * (12 - i);
  }
  Resto = (Soma * 10) % 11;

  if ((Resto == 10) || (Resto == 11))  
  {
    Resto = 0;
  }
  if (Resto != parseInt(numCPF.substring(10, 11)))
  {
    return false;
  }

  return true;
  }

function validar_email(strEmail){
  var re = /\S+@\S+\.\S+/;
  return re.test(strEmail);
}

function checar_required() {
  var fields = $('.required').find('select, textarea, input').serializeArray();
  var FormValido = true;


  $.each(fields, function (i, field) {
    console.log(field.value);
    if (field.value == '') 
    {
      FormValido = false;
    }
  });
  return FormValido;
}

</script>

{% endblock %}
  